name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/docker.yaml
  workflow_dispatch:

env:
  PUSH: ${{ (github.event_name != 'pull_request') && (github.repository == 'apl-ocean-engineering/foxglove-bridge-docker') }}

jobs:
  docker_build:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
      IMAGE_GITHUB_REPO: ${{ github.repository }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        if: env.PUSH == 'true'
        name: Log into registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -
      #   name: Extract Docker metadata
      #   if: env.PUSH == 'true'
      #   id: meta
      #   uses: docker/metadata-action@v5.5.1
      #   with:
      #     images: ghcr.io/${{ github.repository }}
      #     tags: |
      #       type=raw,value=${{ matrix.ROS_DISTRO }}-${{ matrix.stage }}

      - if: github.event_name == 'push'
        name: Build and push (non PR)
        uses: docker/bake-action@v5.7.0
        with:
          push: ${{ env.PUSH }}
          set: |
            *.cache-from=type=gha,scope=foxglove
            *.cache-to=type=gha,scope=foxglove

      - if: github.event_name == 'pull_request'
        name: Build and push (PR)
        uses: docker/bake-action@v5.7.0
        with:
          targets: |
            ${{ matrix.stage }}
          set: |
            *.cache-from=type=gha,scope=foxglove
            *.cache-to=
